### ISSUE TITLE
[BUG] tidyselect .data Deprecation

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTDataOps/REDCapTidieR#50] opened 2022-10-18 19:28 UTC
# Expected Behavior
The `REDCapTidieR` test suite should run free of any `FAIL`s or `WARN`s.

# Current Behavior
There are currently 255 `WARN`s returned when running `devtools::test()` locally since the newest release of `tidyselect` v1.2.0. All warnings look similar to below:

```
Warning (test-utils.R:32): multi_choice_to_labels works
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `"label"` instead of `.data$label`
```

This appears to be a very new issue and one that is still being documented and [discussed in the community](https://community.rstudio.com/t/use-of-data-in-tidyselect-expressions-is-now-deprecated/150092).

And one of Hadley's [most recent commits](https://github.com/r-lib/tidyselect/issues/315).

I'm hesitant to a do a blanket change since R CMD Check in tandem with `rlang` was what prompted introduction of `.data$` into our code in the first place.

## Failure Logs

If applicable, submit any failure logs or error messages here.

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by skadauke** [comment] 2022-10-18 19:32
I guess we could try it in a few places and see what happens? The required change doesn't seem so complicated, does it?

.data$x​ -> x​

?

S


________________________________
From: Rich Hanna ***@***.***>
Sent: Tuesday, October 18, 2022 3:28 PM
To: CHOP-CGTDataOps/REDCapTidieR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External][CHOP-CGTDataOps/REDCapTidieR] [BUG] tidyselect .data Deprecation (Issue #50)


Expected Behavior

The REDCapTidieR test suite should run free of any FAILs or WARNs.

Current Behavior

There are currently 255 WARNs returned when running devtools::test() locally since the newest release of tidyselect v1.2.0. All warnings look similar to below:

Warning (test-utils.R:32): multi_choice_to_labels works
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `"label"` instead of `.data$label`


This appears to be a very new issue and one that is still being documented and discussed in the community<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.rstudio.com%2Ft%2Fuse-of-data-in-tidyselect-expressions-is-now-deprecated%2F150092&data=05%7C01%7Ckadaukes%40chop.edu%7Cd8efe76cb0814cae71ca08dab13f0078%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638017181396428635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1mfPByLGFFDI5W49C50J401t3rg65dUiLkozJRzazO4%3D&reserved=0>.

And one of Hadley's most recent commits<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fr-lib%2Ftidyselect%2Fissues%2F315&data=05%7C01%7Ckadaukes%40chop.edu%7Cd8efe76cb0814cae71ca08dab13f0078%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638017181396428635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vGiMw5e8l%2Fhko8owiraJcIUqtrjRNpUgLrcKAYXh2vE%3D&reserved=0>.

I'm hesitant to a do a blanket change since R CMD Check in tandem with rlang was what prompted introduction of .data$ into our code in the first place.

Failure Logs

If applicable, submit any failure logs or error messages here.

Checklist

Before submitting this issue, please check and verify below that the submission meets the below criteria:

  *    The issue is atomic
  *    The issue description is documented
  *    The issue title describes the problem succinctly
  *    Developers are assigned to the issue
  *    Labels are assigned to the issue

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTDataOps%2FREDCapTidieR%2Fissues%2F50&data=05%7C01%7Ckadaukes%40chop.edu%7Cd8efe76cb0814cae71ca08dab13f0078%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638017181396428635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TzAWXVU61AqI6%2BzGW%2BnoZrsbsFiB090T%2FrqdlP0Q6D4%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWWJO2V6VJNFGVFSX4DWD326ZANCNFSM6AAAAAARIM7KA4&data=05%7C01%7Ckadaukes%40chop.edu%7Cd8efe76cb0814cae71ca08dab13f0078%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638017181396428635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fQHKBgFtUEYQY9uDADs%2BU0HoRPcDRFs2wa7158cYFKU%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by ezraporter** [comment] 2022-10-19 21:23
Had 30 min for a tedious task so I started doing this [here](https://github.com/CHOP-CGTDataOps/REDCapTidieR/tree/fix-tidyselect-warnings) and it isn't that bad.

So far I've found that it's relevant for `select()` and `rename()`. You just have to do `select("x")` instead of `select(.data$x)` and the quoting also takes care of the `check` notes that come up if you just do `select(x)`.

These variants also work fine:
`select("x", "y")`
`select(-"x")`
`rename(!!x = "y")

**Comment by rsh52** [comment] 2022-10-25 13:34
Ah great, I was going to ask if this is recommended, but tested and got back the warning:
```
Warning message:
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
ℹ Please use `""` instead of `.data$`
```
We can apply this across the board then, just hope it doesn't get changed again in the near future.

**Closed** 2022-10-28 11:32 UTC
Labels: bug
